language: php
php:
  - 7.2
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - cp .env.example .env
  - make install
script:
  - make lint
  - make test
env:
  global:
    DB_DATABASE_TEST=travis_ci_test
